### ISSUE TITLE
error message when putting modified firmware on fritz.box

### ISSUE THREAD

**Issue by andrea654** [PeterPawn/modfs#27]
Peter: I am sorry but I was unable to find a good description on how to put shellInABox onto my fritz.box 7490 (with firmware 6.50). So I choose a description I found in a German website and ended up with a message that I did not understand. Googling the message gave me exactly one match that does not tell me anything, now I am stuck. Can you help me (a link how to proceed would be fine).

I managed to get onto fritz.box:8010 and I can login into my fritzbox. I downloaded  modfs-0.4.5.tgz onto /var/mod (joint with some other files like "README.outdated", is that a problem?) and I tried to run
` gunzip -c modfs-0.4.5.tgz | tar x;./modfs   `
from the commandline. The output was

Ermitteln der Hardware-Version ... OK
Prüfen, ob die Hardware-Version unterstützt wird ... OK
Suchen der Einstellung zur Umschaltung auf das alternative System ... OK
Prüfen der aktuell zu startenden Systemversion ... OK
Suchen der aktuellen Kernel-Partition ... OK
Suchen der alternativen Kernel-Partition ... OK
Vergleich der Systeme in den Kernel-Partitionen ... Fehler
Die Flash-Partitionen in der Box enthalten unterschiedliche Versionen der Firmware.
Soll das laufende System in die inaktiven Partitionen kopiert werden? (j/N) N

and since I had no idea whether the last question is a problem I answered with No. How can I proceed from here? Thanks!

**Comment by PeterPawn** [comment]
As far as I understood, you have already a ShellInABox daemon running (on port 8010) and you were able to login to a shell session. What do you want to realize with "modfs" now? From which version are you starting and which version has to be installed (with or without modifications) in the end? 

The (meanwhile) usual way would be an "update" from the installed firmware version to a later one - the selected modifications will be applied to the new filesystem ... but this requires proper parameters for the call.

If you use/call it like you did, it would try to sync the firmware version in the two partition sets and the first step there is a comparision of kernel versions. These versions are different on your device and the message is the question, if the active kernel and filesystem have to be copied to the alternative partition set too. That was a precaution measure in the very early times ... it's unnecessary meanwhile, if it's not the real goal to get two identical systems.

Try "modfs update <new_vendor_image>" instead of a simple "modfs" call and replace the last parameter with the path to a firmware image file from AVM, that you've downloaded earlier from somewhere and stored it on the router itself. 

Another option is a call with "modfs update" ... this way the script tries to find a new version from vendor (using its update information service) and if any newer version was found, it will be downloaded first and then used as template for the new system.

But once more ... a better place to get help, how to use "modfs" nowadays, is the bulletin board mentioned above. A comprehensive (and exhaustive) description will not fit into the "issues" section here - I know, that there's no usable (english) documentation for the current version. For german-speaking users, the IPPF (http://www.ip-phone-forum.de/showthread.php?t=273304) is the right place to find a description and comments from other users - but questions in English are welcome too.

It is no longer worthwhile to write an additional documention for the current version ... the first version (which is meanwhile "outdated" and was removed from the very current archive) will not help anymore. 

I want to publish a new, extended and more modern version of "modfs" - any additional (personal) efforts invested into a new description (for the current version) are lost in final. 

If somebody writes a help or "HowTo" for it (in english), I'll add it - but I've not the needed time to write it myself. 

For german readers there's again (or already :-)) a beginners guide in the bulletin board system.

**Comment by andreasloe** [comment]
Thanks!
